### ISSUE TITLE
Failing due to modified package-lock.json

### ISSUE THREAD

**Issue by clarktlaugh** [steve-gray/semantique#1]
Hello,

I'm having an issue using `semantique` in my drone pipeline:

```
pipeline:
  tests:
    image: node
    commands:
      - npm install
      - npm run lint
      - npm test

  update-semantic-versioning:
    image: eventualconsistency/semantique
    pull: true
    secrets: [ git_pass, git_user ]
    when:
      branch: [ master ]
      event: [ push ]

  npm-publish:
    image: plugins/npm
    registry: https://registry.npmjs.itcs.hpecorp.net
    secrets: [ npm_token, github_token ]
    when:
      branch: [ master ]
      event: [ tag ]
```

It seems to be failing due to the fact that npm is writing out a modified `package-lock.json`:

```

===========================================================================================
   _____   ______   __  __              _   _   _______   _____    ____    _    _   ______ 
  / ____| |  ____| |  \/  |     /\     | \ | | |__   __| |_   _|  / __ \  | |  | | |  ____|
 | (___   | |__    | \  / |    /  \    |  \| |    | |      | |   | |  | | | |  | | | |__   
  \___ \  |  __|   | |\/| |   / /\ \   | . ` |    | |      | |   | |  | | | |  | | |  __|  
  ____) | | |____  | |  | |  / ____ \  | |\  |    | |     _| |_  | |__| | | |__| | | |____ 
 |_____/  |______| |_|  |_| /_/    \_\ |_| \_|    |_|    |_____|  \___\_\  \____/  |______|
===========================================================================================
 -> Checking workspace for uncommitted changes.
The workspace contains 1 non-committed changes.
 -> CHANGED: package-lock.json

exit code: 254
```

Do you have a suggestion for how to handle this?
